---
- name: Install Elasticsearch dependencies
  yum: name={{ item }} state=installed
  with_items: elasticsearch.yum.dependencies

- name: Check elasticsearch installed
  yum: name=elasticsearch state=installed
  register: elasticsearch_installed
  ignore_errors: yes

- name: Fetch Elasticsearch
  action: get_url url={{ elasticsearch.url }}/{{ elasticsearch.yum.package }} dest={{ elasticsearch.tmp }}
          mode=0440
  register: elasticsearch_yum
  when: elasticsearch_installed|failed

- name: Install Elasticsearch package
  yum: name={{ elasticsearch.tmp }}/{{ elasticsearch.yum.package }}
  when: elasticsearch_installed|failed

- name: Change Elasticsearch bind IP
  lineinfile: "dest='{{ elasticsearch.config }}' state=present regexp='^network.host'
              insertafter='# network.host'  line='network.host: {{ elasticsearch_ip }}'"
  notify: "Restart Elasticsearch"

  # TODO: přejmenovat elasticsearch cluster name na něco rozumného
- name: Change Elasticsearch name
  lineinfile: "dest='{{ elasticsearch.config }}' state=present regexp='^network.host'
              insertafter='# network.host'  line='network.host: {{ elasticsearch_ip }}'"
  notify: "Restart Elasticsearch"


- name: "Ensure Elasticsearch is running"
  service: name={{ elasticsearch.yum.service }} state=started enabled=yes