---
# Install Elasticsearch
- include: elasticsearch_deb.yml
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

- include: elasticsearch_yum.yml
  when: ansible_distribution in [ 'CentOS' ]


# Install Paramedic dashboard
#- include: paramedic.yml tags=elasticsearch
#  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]